language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
before_script: grunt build
after_success:
  - '[ -n "$TRAVIS_TAG" ] && sudo apt-get update -qq'
  - '[ -n "$TRAVIS_TAG" ] && sudo apt-get install -y devscripts debhelper rpm'
  - '[ -n "$TRAVIS_TAG" ] && grunt debian_package'
  - '[ -n "$TRAVIS_TAG" ] && grunt rpm:release'
  - '[ -n "$TRAVIS_TAG" ] && cp -r dist puppetexplorer-$TRAVIS_TAG'
  - '[ -n "$TRAVIS_TAG" ] && tar czf puppetexplorer-$TRAVIS_TAG.tar.gz puppetexplorer-$TRAVIS_TAG'

deploy:
  - provider: s3
    access_key_id: AKIAJEZEAAG2CU6PZHTQ
    secret_access_key:
      secure: Nd9tsVNDsUMEDveeKMCZHj4nEv2zM4Y0Y+gTF47JQ2bRWKS9fSWrSfISvm72VKhMrBrpDFyL/sVzLe7nrDyxqJSdKdGm1o6bPPcKDnREwUpVipbMVTpo4wLTJ1RnfuVsvQR9N1xeGVEWFM+wVSerbDVIcr3LGmWxQCfZCLus6rM=
    bucket: puppetexplorer
    skip_cleanup: true
    local-dir: dist
    acl: public_read
    on:
      branch: master
      repo: spotify/puppetexplorer
  - provider: releases
    edge: true
    api_key:
      secure: fIuXoPBhqJem2JIjw4aLm/kU81zhwquRoHGw0QHI5j+VSPQtxxj9u+AO+csFu+M92gLZRT2fz8TIjYm+1K1UZrIaSkEpGiOVqVo1mEbAhq2wAIbmXo8OyOjDOkpAaQ+FOV1VjuyBI+7+85izQ3HnMvgqONiwS9Xd2pM+HYLfRG4=
    file:
      - tmp/puppetexplorer*.deb
      - rpm/RPMS/noarch/puppetexplorer*.rpm
      - puppetexplorer-*.tar.gz
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      repo: spotify/puppetexplorer
