language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
before_script: grunt build

deploy:
  - provider: s3
    access_key_id: AKIAJEZEAAG2CU6PZHTQ
    secret_access_key:
      secure: Nd9tsVNDsUMEDveeKMCZHj4nEv2zM4Y0Y+gTF47JQ2bRWKS9fSWrSfISvm72VKhMrBrpDFyL/sVzLe7nrDyxqJSdKdGm1o6bPPcKDnREwUpVipbMVTpo4wLTJ1RnfuVsvQR9N1xeGVEWFM+wVSerbDVIcr3LGmWxQCfZCLus6rM=
    bucket: puppetexplorer
    skip_cleanup: true
    local-dir: dist
    acl: public_read
    on:
      branch: master
      repo: spotify/puppetexplorer
